# Generated by Django 5.1.6 on 2025-02-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_id_alter_user_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(help_text='Email or phone number', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], editable=False, help_text='Identifier type', max_length=10),
        ),
    ]
